// GENERATED by the DS-portal usage scan (2026-07-18) — imports of
// @/components/ds/ui, @/components/ui/panels and @/components/ui/primitives
// across app/, components/, lib/. Regenerate with the scan snippet in
// components/design-system/README.md when call sites move.
export const DS_USAGE: Record<string, string[]> = {
  "Avatar": [
    "app/dev-preview/ds/page.tsx",
    "components/ui/primitives.tsx"
  ],
  "Badge": [
    "app/dev-preview/ds-shadcn/page.tsx"
  ],
  "Button": [
    "app/dev-preview/ds-shadcn/page.tsx",
    "app/dev-preview/ds/page.tsx",
    "components/auth/sign-out-button.tsx",
    "components/calendar/event-composer.tsx",
    "components/documents/database-view.tsx",
    "components/horizon/horizon-view.tsx",
    "components/tasks/tasks-view.tsx",
    "components/today/habits-section.tsx",
    "components/today/schedule-section.tsx",
    "components/today/today-view.tsx",
    "components/ui/primitives.tsx",
    "components/ui/zen.tsx"
  ],
  "Card": [
    "app/dev-preview/ds/page.tsx",
    "components/ui/primitives.tsx"
  ],
  "Checkbox": [
    "app/dev-preview/ds-shadcn/page.tsx",
    "app/dev-preview/ds/page.tsx",
    "components/ui/primitives.tsx"
  ],
  "Divider": [
    "app/dev-preview/ds-shadcn/page.tsx",
    "app/dev-preview/ds/page.tsx",
    "components/ui/primitives.tsx"
  ],
  "DropdownMenu": [
    "app/dev-preview/ds-shadcn/page.tsx"
  ],
  "DropdownMenuContent": [
    "app/dev-preview/ds-shadcn/page.tsx"
  ],
  "DropdownMenuItem": [
    "app/dev-preview/ds-shadcn/page.tsx"
  ],
  "DropdownMenuSeparator": [
    "app/dev-preview/ds-shadcn/page.tsx"
  ],
  "DropdownMenuTrigger": [
    "app/dev-preview/ds-shadcn/page.tsx"
  ],
  "EmptyState": [
    "components/tasks/tasks-view.tsx",
    "components/today/habits-section.tsx",
    "components/today/schedule-section.tsx",
    "components/today/today-view.tsx"
  ],
  "Field": [
    "app/dev-preview/ds-shadcn/page.tsx",
    "app/dev-preview/ds/page.tsx"
  ],
  "FigmaTag": [
    "components/tasks/tasks-view.tsx",
    "components/today/today-view.tsx"
  ],
  "Icon": [
    "app/dev-preview/ds-shadcn/page.tsx",
    "app/dev-preview/ds/page.tsx",
    "app/login/page.tsx",
    "components/calendar/calendar-sidebar.tsx",
    "components/calendar/calendar-view.tsx",
    "components/calendar/event-composer.tsx",
    "components/calendar/mini-month.tsx",
    "components/clients/clients-view.tsx",
    "components/documents/block-editor.tsx",
    "components/documents/cover-picker.tsx",
    "components/documents/database-view.tsx",
    "components/documents/doc-properties.tsx",
    "components/documents/documents-view.tsx",
    "components/documents/rich-text.tsx",
    "components/focus/focus-view.tsx",
    "components/horizon/horizon-view.tsx",
    "components/inbox/inbox-view.tsx",
    "components/inbox/triage.tsx",
    "components/money/invoice-detail.tsx",
    "components/money/money-view.tsx",
    "components/onboarding/onboarding-flow.tsx",
    "components/portal/portal-document.tsx",
    "components/projects/preview-overlay.tsx",
    "components/projects/project-docs.tsx",
    "components/projects/projects-workspace.tsx",
    "components/projects/requests-tab.tsx",
    "components/projects/share-panel.tsx",
    "components/rituals/ritual-flow.tsx",
    "components/settings/appearance.tsx",
    "components/settings/connections.tsx",
    "components/settings/settings-view.tsx",
    "components/shell/app-shell.tsx",
    "components/shell/command-palette.tsx",
    "components/shell/new-space-modal.tsx",
    "components/shell/quick-capture.tsx",
    "components/shell/theme-toggle.tsx",
    "components/shell/view-placeholder.tsx",
    "components/shell/view-width.tsx",
    "components/task-detail/task-detail-drawer.tsx",
    "components/tasks/task-row.tsx",
    "components/tasks/task-view-toggle.tsx",
    "components/tasks/tasks-view.tsx",
    "components/today/habits-section.tsx",
    "components/today/schedule-section.tsx",
    "components/today/today-view.tsx",
    "components/ui/emoji-picker.tsx",
    "components/ui/page-header.tsx",
    "components/ui/page-icon.tsx",
    "components/ui/panel.tsx",
    "components/ui/popover.tsx",
    "components/ui/primitives.tsx",
    "components/ui/select.tsx",
    "components/ui/states.tsx",
    "components/ui/upload-zone.tsx",
    "components/ui/zen.tsx",
    "components/week/week-view.tsx"
  ],
  "IconButton": [
    "app/dev-preview/ds-shadcn/page.tsx",
    "app/dev-preview/ds/page.tsx",
    "components/calendar/calendar-sidebar.tsx",
    "components/shell/app-shell.tsx",
    "components/ui/primitives.tsx"
  ],
  "Input": [
    "app/dev-preview/ds/page.tsx",
    "components/money/invoice-detail.tsx",
    "components/money/money-view.tsx",
    "components/portal/portal-document.tsx",
    "components/settings/settings-view.tsx",
    "components/shell/new-space-modal.tsx"
  ],
  "Kbd": [
    "app/dev-preview/ds/page.tsx",
    "components/shell/command-palette.tsx",
    "components/ui/primitives.tsx"
  ],
  "Logo": [
    "app/dev-preview/ds-shadcn/page.tsx",
    "components/shell/app-shell.tsx"
  ],
  "Mark": [
    "app/dev-preview/ds-shadcn/page.tsx",
    "app/login/page.tsx",
    "components/shell/app-shell.tsx",
    "components/today/today-view.tsx"
  ],
  "Panel": [
    "components/today/habits-section.tsx",
    "components/today/schedule-section.tsx",
    "components/today/today-view.tsx"
  ],
  "PanelBody": [
    "components/today/habits-section.tsx",
    "components/today/schedule-section.tsx",
    "components/today/today-view.tsx"
  ],
  "PanelHeader": [
    "components/today/habits-section.tsx",
    "components/today/schedule-section.tsx",
    "components/today/today-view.tsx"
  ],
  "Pill": [
    "app/dev-preview/ds/page.tsx"
  ],
  "Popover": [
    "app/dev-preview/ds-shadcn/page.tsx"
  ],
  "PopoverContent": [
    "app/dev-preview/ds-shadcn/page.tsx"
  ],
  "PopoverTrigger": [
    "app/dev-preview/ds-shadcn/page.tsx"
  ],
  "PriorityBars": [
    "components/tasks/tasks-view.tsx"
  ],
  "QuickAddRow": [
    "components/focus/focus-view.tsx",
    "components/tasks/tasks-view.tsx"
  ],
  "Select": [
    "app/dev-preview/ds-shadcn/page.tsx"
  ],
  "Spinner": [
    "app/dev-preview/ds/page.tsx"
  ],
  "SplitButton": [
    "components/ui/primitives.tsx"
  ],
  "Switch": [
    "app/dev-preview/ds-shadcn/page.tsx",
    "components/ui/primitives.tsx"
  ],
  "SwitchTrack": [
    "components/projects/share-panel.tsx",
    "components/shell/view-width.tsx"
  ],
  "Tabs": [
    "app/dev-preview/ds-shadcn/page.tsx"
  ],
  "Tag": [
    "app/dev-preview/ds-shadcn/page.tsx",
    "components/tasks/task-row.tsx",
    "components/ui/primitives.tsx"
  ],
  "TextInput": [
    "app/dev-preview/ds-shadcn/page.tsx"
  ],
  "Textarea": [
    "components/portal/portal-document.tsx"
  ],
  "Toggle": [
    "app/dev-preview/ds/page.tsx",
    "components/calendar/event-composer.tsx",
    "components/settings/appearance.tsx"
  ],
  "Tooltip": [
    "app/dev-preview/ds-shadcn/page.tsx",
    "app/dev-preview/ds/page.tsx",
    "components/ui/emoji-picker.tsx",
    "components/ui/primitives.tsx"
  ],
  "TooltipProvider": [
    "app/dev-preview/ds-shadcn/page.tsx",
    "components/shell/providers.tsx",
    "components/today/today-view.tsx"
  ]
};
