// Extracts the Phosphor glyphs the film uses (the same icon family as the
// Zenboard sidebar) into src/brand/glyphs.generated.ts, so the film has no
// runtime icon dependency. Duotone gives two layers: the 20%-opacity shape
// becomes the fillable area, the rest is linework.
//
//   node scripts/extract-glyphs.mjs
import { readFileSync, writeFileSync } from "node:fs";

const ROOT = new URL("../node_modules/@phosphor-icons/core/assets/", import.meta.url);
const NAMES = [
  "list-checks", "kanban", "file-text", "notepad", "calendar-blank", "receipt", "users", "sun-horizon",
  "key", "check", "lightbulb", "clock", "paper-plane-tilt", "command", "arrow-right",
];

const paths = (svg) => [...svg.matchAll(/<path d="([^"]+)"( opacity="0.2")?\/>/g)];
const out = {};
for (const name of NAMES) {
  const duo = readFileSync(new URL(`duotone/${name}-duotone.svg`, ROOT), "utf8");
  const reg = readFileSync(new URL(`regular/${name}.svg`, ROOT), "utf8");
  const solid = readFileSync(new URL(`fill/${name}-fill.svg`, ROOT), "utf8");
  out[name] = {
    fill: paths(duo).filter((m) => m[2]).map((m) => m[1]),
    line: paths(duo).filter((m) => !m[2]).map((m) => m[1]),
    regular: paths(reg).map((m) => m[1]),
    solid: paths(solid).map((m) => m[1]),
  };
}
const body = `// GENERATED by scripts/extract-glyphs.mjs from @phosphor-icons/core (MIT). Do not edit.
// viewBox 0 0 256 256. fill/line = duotone layers, regular = outline, solid = the filled icon.
export const GLYPHS = ${JSON.stringify(out, null, 2)} as const;

export type GlyphName = keyof typeof GLYPHS;
`;
writeFileSync(new URL("../src/brand/glyphs.generated.ts", import.meta.url), body);
console.log("wrote", NAMES.length, "glyphs");
