"""Measures when every word of every voice-over clip is spoken, so on-screen
words can appear exactly as they are heard.

    python3 scripts/vo-words.py     # needs faster-whisper

Writes src/brand/vo-words.generated.ts: per clip, each word with its start and
end in seconds from the start of the clip.
"""
import glob
import json
import os

from faster_whisper import WhisperModel

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
model = WhisperModel("base.en", device="cpu", compute_type="int8")
out = {}
for path in sorted(glob.glob(os.path.join(ROOT, "public/vo/*.mp3"))):
    clip = os.path.splitext(os.path.basename(path))[0]
    segs, _ = model.transcribe(path, word_timestamps=True, beam_size=5, vad_filter=False)
    out[clip] = [{"w": w.word.strip(), "s": round(w.start, 3), "e": round(w.end, 3)} for s in segs for w in s.words]
    print(clip, " ".join(f"{w['w']}@{w['s']}" for w in out[clip]))
body = "// GENERATED by scripts/vo-words.py from public/vo/*.mp3. Do not edit.\n"
body += "// Seconds from the start of each clip.\n"
body += "export const VO_WORDS: Record<string, { w: string; s: number; e: number }[]> = " + json.dumps(out, indent=2) + ";\n"
open(os.path.join(ROOT, "src/brand/vo-words.generated.ts"), "w").write(body)
